import Chrome from '@/components/apps/Chrome'
import Discord from '@/components/apps/Discord'
import Figma from '@/components/apps/Figma'
import Finder from '@/components/apps/Finder'
import Placeholder from '@/components/apps/Placeholder'
import VSCode from '@/components/apps/VSCode'

import bin from '@/assets/apps/bin.png'
import bitwarden from '@/assets/apps/bitwarden.png'
import chrome from '@/assets/apps/chrome.png'
import discord from '@/assets/apps/discord.png'
import docker from '@/assets/apps/docker.png'
import figma from '@/assets/apps/figma.png'
import finder from '@/assets/apps/finder.png'
import iterm2 from '@/assets/apps/iterm2.png'
import obsidian from '@/assets/apps/obsidian.png'
import spotify from '@/assets/apps/spotify.png'
import vscode from '@/assets/apps/vscode.png'

import { App, AppsConfig, Menubar, SubMenuType } from '@/types/apps'

const defaultMinWidthHeight = {
  minWidth: 650,
  minHeight: 400,
}

export const AppWindowConfig: AppsConfig = {
  [App.FINDER]: {
    width: 1024,
    height: 576,
    ...defaultMinWidthHeight,
    component: Finder,
  },
  [App.CHROME]: {
    width: 1366,
    height: 768,
    ...defaultMinWidthHeight,
    component: Chrome,
  },
  [App.BIN]: {
    width: 1024,
    height: 576,
    disabled: true,
    component: Placeholder,
  },
  [App.DISCORD]: {
    width: 1024,
    height: 576,
    minWidth: 300,
    minHeight: 300,
    component: Discord,
  },
  [App.DOCKER]: {
    width: 1024,
    height: 576,
    disabled: true,
    component: Placeholder,
  },
  [App.BITWARDEN]: {
    width: 1024,
    height: 576,
    disabled: true,
    component: Placeholder,
  },
  [App.FIGMA]: {
    width: 1366,
    height: 768,
    ...defaultMinWidthHeight,
    component: Figma,
  },
  [App.ITERM2]: {
    width: 800,
    height: 600,
    disabled: true,
    component: Placeholder,
  },
  [App.OBSIDIAN]: {
    width: 1366,
    height: 768,
    disabled: true,
    component: Placeholder,
  },
  [App.SPOTIFY]: {
    width: 1024,
    height: 576,
    disabled: true,
    component: Placeholder,
  },
  [App.VSCODE]: {
    width: 1366,
    height: 768,
    component: VSCode,
  },
}

export const AppIcon = {
  [App.FINDER]: finder,
  [App.BIN]: bin,
  [App.BITWARDEN]: bitwarden,
  [App.CHROME]: chrome,
  [App.DISCORD]: discord,
  [App.FIGMA]: figma,
  [App.ITERM2]: iterm2,
  [App.OBSIDIAN]: obsidian,
  [App.SPOTIFY]: spotify,
  [App.VSCODE]: vscode,
  [App.DOCKER]: docker,
}

export const AppMenubar: Menubar = {
  [App.FINDER]: [
    {
      label: App.FINDER,
      submenu: [
        { label: 'About Finder' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Settings...', shortcut: '⌘ N' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Empty Bin...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Services' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Finder', shortcut: '⌘ H' },
        { label: 'Hide Others' },
        { label: 'Show All', shortcut: '⌘ A' },
      ],
    },
    {
      label: 'File',
      submenu: [
        { label: 'New Finder Window', shortcut: '⌘ N' },
        { label: 'New Folder' },
        { label: 'New Folder with Selection' },
        { label: 'New Smart Folder' },
        { label: 'New Tab', shortcut: '⌘ T' },
        { label: 'Open', shortcut: '⌘ O' },
        { label: 'Open With', shortcut: '⌘ N' },
        { label: 'Close Window', shortcut: '⌘ W' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Get Info', shortcut: '⌘ I' },
        { label: 'Rename' },
        { label: 'Compress' },
        { label: 'Duplicate', shortcut: '⌘ D' },
        { label: 'Make Alias', shortcut: '⌘ A' },
        { label: 'Quick Look "Desktop"', shortcut: '⌘ Y' },
        { label: 'Print', shortcut: '⌘ P' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Share...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Original', shortcut: '⌘ R' },
        { label: 'Add to Dock', shortcut: '⌘ T' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo', shortcut: '⌘ Z' },
        { label: 'Redo' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Cut', shortcut: '⌘ X' },
        { label: 'Copy', shortcut: '⌘ C' },
        { label: 'Paste', shortcut: '⌘ V' },
        { label: 'Select All', shortcut: '⌘ A' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Clipboard' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Start Dictation...' },
        { label: 'Emoji & Symbols' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { label: 'as icons', shortcut: '⌘ 1' },
        { label: 'as List', shortcut: '⌘ 2' },
        { label: 'as Columns', shortcut: '⌘ 3' },
        { label: 'as Gallery', shortcut: '⌘ 4' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Use Groups', shortcut: '⌘ 0' },
        { label: 'Sort By' },
        { label: 'Clean Up' },
        { label: 'Clean Up By' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Sidebar', shortcut: '⌘ S' },
        { label: 'Show Preview', shortcut: '⌘ P' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Toolbar', shortcut: '⌘ T' },
        { label: 'Show All Tabs', shortcut: '⌘ /' },
        { label: 'Hide Path Bar', shortcut: '⌘ P' },
        { label: 'Hide Status Bar' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Customise Toolbar...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show View Options', shortcut: '⌘ J' },
        { label: 'Show Preview Options' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Enter Full Screen' },
      ],
    },
    {
      label: 'Go',
      submenu: [
        { label: 'Back', shortcut: '⌘ [' },
        { label: 'Forward', shortcut: '⌘ ]' },
        { label: 'Select Startup Disk' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Recents', shortcut: '⌘ F' },
        { label: 'Documents', shortcut: '⌘ O' },
        { label: 'Desktop', shortcut: '⌘ D' },
        { label: 'Downloads', shortcut: '⌘ L' },
        { label: 'Home', shortcut: '⌘ H' },
        { label: 'Computer', shortcut: '⌘ C' },
        { label: 'AirDrop', shortcut: '⌘ R' },
        { label: 'Network', shortcut: '⌘ K' },
        { label: 'iCloud Drive', shortcut: '⌘ I' },
        { label: 'Shared', shortcut: '⌘ S' },
        { label: 'Applications', shortcut: '⌘ A' },
        { label: 'Utilities', shortcut: '⌘ U' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Recent Folders' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Go to Folder...', shortcut: '⌘ G' },
        { label: 'Connect to Server...', shortcut: '⌘ K' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { label: 'Minimize', shortcut: '⌘ M' },
        { label: 'Zoom' },
        { label: 'Tile Window to Left of Screen' },
        { label: 'Tile Window to Right of Screen' },
        { label: 'Replace Tiled Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Remove Window from Set' },
        { label: 'Cycle Through Windows', shortcut: '⌘ `' },
        { label: 'Show Progress Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Previous Tab' },
        { label: 'Show Next Tab' },
        { label: 'Move Tab to New Window' },
        { label: 'Merge All Windows' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring All to Front' },
        { type: SubMenuType.SEPARATOR },
        { label: 'zigamacele' },
      ],
    },
    {
      label: 'Help',
      submenu: [{ label: 'Tips for Your Mac' }, { label: 'macOS Help' }],
    },
  ],
  [App.CHROME]: [
    {
      label: App.CHROME,
      submenu: [
        { label: 'About Google Chrome' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Settings...', shortcut: '⌘ ,' },
        { label: 'Clear Browsing Data...' },
        { label: 'Import Bookmarks and Settings...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Services' },
        { label: 'Hide Google Chrome', shortcut: '⌘ H' },
        { label: 'Hide Others' },
        { label: 'Show all' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Warn Before Quitting (⌘Q)' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Quit Google Chrome', shortcut: '⌘ Q' },
      ],
    },
    {
      label: 'File',
      submenu: [
        { label: 'New Tab', shortcut: '⌘ T' },
        { label: 'New Window', shortcut: '⌘ N' },
        { label: 'New Incognito Window' },
        { label: 'Re-open Closed Tab' },
        { label: 'Open File...', shortcut: '⌘ O' },
        { label: 'Open Location...', shortcut: '⌘ L' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Close Window' },
        { label: 'Close Tab', shortcut: '⌘ W' },
        { label: 'Save Page As...', shortcut: '⌘ S' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Share' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Print', shortcut: '⌘ P' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo', shortcut: '⌘ Z' },
        { label: 'Redo' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Cut', shortcut: '⌘ X' },
        { label: 'Copy', shortcut: '⌘ C' },
        { label: 'Paste', shortcut: '⌘ V' },
        { label: 'Select All', shortcut: '⌘ A' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Clipboard' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Start Dictation...' },
        { label: 'Emoji & Symbols' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { label: 'Always Show Bookmarks Bar', shortcut: '⌘ B' },
        { label: 'Always Show Toolbar in Full Screen', shortcut: '⌘ F' },
        { label: 'Always Show Full URLs' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Stop', shortcut: '⌘ .' },
        { label: 'Force Reload This Page', shortcut: '⌘ R' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Enter Full Screen' },
        { label: 'Actual Size', shortcut: '⌘ O' },
        { label: 'Zoom In', shortcut: '⌘ +' },
        { label: 'Zoom Out', shortcut: '⌘ -' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Cast...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Developer' },
      ],
    },
    {
      label: 'History',
      submenu: [
        { label: 'Home', shortcut: '⌘ H' },
        { label: 'Back', shortcut: '⌘ [' },
        { label: 'Forward', shortcut: '⌘ ]' },
      ],
    },
    {
      label: 'Bookmarks',
      submenu: [
        { label: 'Bookmark Manager', shortcut: '⌘ B' },
        { label: 'Bookmark This Tab...', shortcut: '⌘ D' },
        { label: 'Bookmark All Tabs...' },
      ],
    },
    {
      label: 'Tabs',
      submenu: [
        { label: 'New Tab to the Right' },
        { label: 'Select Next Tab' },
        { label: 'Select Previous Tab' },
        { label: 'Duplicate tab' },
        { label: 'Mute site' },
        { label: 'Pin Tab' },
        { label: 'Group Tab' },
        { label: 'Close Other Tabs' },
        { label: 'Close Tabs to the Right' },
        { label: 'Move Tab to New Window' },
        { label: 'Search Tabs..' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { label: 'Minimize', shortcut: '⌘ M' },
        { label: 'Zoom' },
        { label: 'Tile Window to Left of Screen' },
        { label: 'Tile Window to Right of Screen' },
        { label: 'Replace Tiled Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Remove Window from Set' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Move to Built-in Retina Display' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show As Tab' },
        { label: 'Name Window...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Downloads', shortcut: '⌘ J' },
        { label: 'Extensions' },
        { label: 'Task Manager' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring All to Front' },
      ],
    },
    {
      label: 'Help',
      submenu: [
        { label: 'Report an Issue...', shortcut: '⌘ I' },
        { label: 'Google Chrome Help' },
      ],
    },
  ],
  [App.DISCORD]: [
    {
      label: App.DISCORD,
      submenu: [
        { label: 'About Discord' },
        { label: 'Check for Updates…' },
        { label: 'Acknowledgements' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Settings...', shortcut: '⌘ ,' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Services' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Discord', shortcut: '⌘ H' },
        { label: 'Hide Others' },
        { label: 'Show all' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Quit', shortcut: '⌘ Q' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo', shortcut: '⌘ Z' },
        { label: 'Redo' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Cut', shortcut: '⌘ X' },
        { label: 'Copy', shortcut: '⌘ C' },
        { label: 'Paste', shortcut: '⌘ V' },
        { label: 'Select All', shortcut: '⌘ A' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Clipboard' },
        { type: SubMenuType.SEPARATOR },
        { label: 'AutoFill' },
        { label: 'Start Dictation...' },
        { label: 'Emoji & Symbols' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { label: 'Reload', shortcut: '⌘ R' },
        { label: 'Toggle Full Screen', shortcut: '⌘ F' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { label: 'Minimize', shortcut: '⌘ M' },
        { label: 'Zoom' },
        { label: 'Close', shortcut: '⌘ W' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring All to Front' },
      ],
    },
    {
      label: 'Help',
      submenu: [{ label: 'Discord Help' }],
    },
  ],
  [App.FIGMA]: [
    {
      label: App.FIGMA,
      submenu: [
        { label: 'About Figma' },
        { label: 'Check for Updates…' },
        { label: 'Acknowledgements' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Settings...', shortcut: '⌘ ,' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Quick Actions...', shortcut: '⌘ /' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Services' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Figma', shortcut: '⌘ H' },
        { label: 'Hide Others' },
        { label: 'Show all' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Quit Figma', shortcut: '⌘ Q' },
      ],
    },
    {
      label: 'File',
      submenu: [
        { label: 'New Window', shortcut: '⌘ N' },
        { label: 'New Tab', shortcut: '⌘ T' },
        { label: 'Open File Browser', shortcut: '⌘ O' },
        { label: 'Open File URL From Clipboard' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Close Window' },
        { label: 'Close Tab', shortcut: '⌘ W' },
        { label: 'Reopen Closed Tab', shortcut: '⌘ T' },
        { label: 'Recently Closed Tab' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Share' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Export...', shortcut: '⌘ E' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo' },
        { label: 'Redo' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Playing in p' },
        { label: 'Cut' },
        { label: 'Copy' },
        { label: 'Copy As' },
        { label: 'Paste' },
        { label: 'Paste Over Selection' },
        { label: 'Paste to Replace' },
        { label: 'Duplicate' },
        { label: 'Delete' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Find...' },
        { label: 'Find Next' },
        { label: 'Find Previous' },
        { label: 'Find and Replace...' },
        { label: 'Set Default Properties' },
        { label: 'Copy Properties' },
        { label: 'Paste Properties' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Pick Color' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Select All' },
        { label: 'Select None' },
        { label: 'Select Inverse' },
        { label: 'Select All Matching Layers' },
        { label: 'Select All With' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Auto Fill' },
        { label: 'Start Dictation...' },
        { label: 'Emoji & Symbols' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { label: 'Pixel Grid' },
        { label: 'Layout Grids' },
        { label: 'Rulers' },
        { label: 'Show Slices' },
        { label: 'Comments' },
        { label: 'Outlines' },
        { label: 'Pixel Preview' },
        { label: 'Mask Outlines' },
        { label: 'Frame Outlines' },
        { label: 'Memory Usage' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show/Hide UI' },
        { label: 'Multiplayer Cursors' },
        { label: 'Open Dev Mode' },
        { label: 'Panels' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Zoom In' },
        { label: 'Zoom Out' },
        { label: 'Zoom to 100%' },
        { label: 'Zoom to Fit' },
        { label: 'Zoom to Selection' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Previous Page' },
        { label: 'Next Page' },
        { label: 'Zoom to Previous Frame' },
        { label: 'Zoom to Next Frame' },
        { label: 'Find Previous Frame' },
        { label: 'Find Next Frame' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Interface Scale' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Just Chatting' },
        { label: 'Toggle Full Screen' },
        { label: 'Always Show Tabs When Presenting' },
      ],
    },
    {
      label: 'Object',
      submenu: [
        { label: 'Group Selection' },
        { label: 'Wrap in New Section' },
        { label: 'Convert to Section' },
        { label: 'Convert to Frame' },
        { label: 'Frame Selection' },
        { label: 'Ungroup Selection' },
        { label: 'Use as mask' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Add Auto Layout' },
        { label: 'Create Component' },
        { label: 'Reset All Changes' },
        { label: 'Detach Instance' },
        { label: 'Main Component' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring to Front' },
        { label: 'Bring Forward' },
        { label: 'Send Backward' },
        { label: 'Send to Back' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Flip Horizontal' },
        { label: 'Flip Vertical' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Rotate 180°' },
        { label: 'Rotate 90° Left' },
        { label: 'Rotate 90° Right' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Flatten Selection' },
        { label: 'Outline Stroke' },
        { label: 'Boolean Groups' },
        { label: 'Rasterize Selection' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show/Hide Selection' },
        { label: 'Lock/Unlock Selection' },
        { label: 'Hide Other Layers' },
        { label: 'Collapse Layers' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Remove Fill' },
        { label: 'Remove Stroke' },
        { label: 'Swap Fill and Stroke' },
      ],
    },
    {
      label: 'Text',
      submenu: [
        { label: 'Bold' },
        { label: 'Italic' },
        { label: 'Underline' },
        { label: 'Strikethrough' },
        { label: 'Create Link' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bulleted List' },
        { label: 'Numbered List' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Alignment' },
        { label: 'Adjust' },
        { label: 'Case' },
        { label: 'Text Direction' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Spell Check' },
      ],
    },
    {
      label: 'Arrange',
      submenu: [
        { label: 'Round to Pixel' },
        { label: 'Align Left', shortcut: 'TA' },
        { label: 'Align Horizontal Centers', shortcut: 'TH' },
        { label: 'Align Right' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Align Top', shortcut: 'TW' },
        { label: 'Align Vertical Centers', shortcut: 'TV' },
        { label: 'Align Bottom', shortcut: 'TS' },
        { label: 'Tidy Up' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Pack Horizontal' },
        { label: 'Pack Vertical' },
        { label: 'Distribute Horizontal Spacing' },
        { label: 'Distribute Vertical Spacing' },
        { label: 'Distribute Left' },
        { label: 'Distribute Horizontal Centers' },
        { label: 'Distribute Right' },
        { label: 'Distribute Top' },
        { label: 'Distribute Vertical Centers' },
        { label: 'Distribute Bottom' },
        { type: SubMenuType.SEPARATOR },
        { label: 'New Window', shortcut: '⌘ N' },
        { label: 'New Tab', shortcut: '⌘ T' },
        { label: 'Open File Browser', shortcut: '⌘ O' },
        { label: 'Open File URL From Clipboard' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Close Window' },
        { label: 'Close Tab', shortcut: '⌘ W' },
        { label: 'Reopen Closed Tab', shortcut: '⌘ T' },
        { label: 'Recently Closed Tab' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Share' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Export...', shortcut: '⌘ E' },
      ],
    },
    {
      label: 'Vector',
      submenu: [
        { label: 'Run last plugin' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Saved plugins' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Development' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Manage plugins...' },
      ],
    },
    {
      label: 'Plugins',
      submenu: [
        { label: 'Run last plugin' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Saved plugins' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Development' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Manage plugins...' },
      ],
    },
    {
      label: 'Widgets',
      submenu: [
        { label: 'Manage widgets...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Select all widgets' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Development' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { label: 'Minimize', shortcut: '⌘ M' },
        { label: 'Zoom' },
        { label: 'Tile Window to Left of Screen' },
        { label: 'Tile Window to Right of Screen' },
        { label: 'Replace Tiled Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Remove Window from Set' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Select Previous Tab' },
        { label: 'Select Next Tab' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring All to Front' },
      ],
    },
    {
      label: 'Help',
      submenu: [
        { label: 'Help Page' },
        { label: 'Keyboard Shortcuts' },
        { label: 'Support Forum' },
        { label: 'Video Tutorials' },
        { label: 'Release Notes' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Troubleshooting' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Legal Summary' },
        { label: 'Account Settings' },
        { label: 'Log Out' },
      ],
    },
  ],
  [App.VSCODE]: [
    {
      label: App.VSCODE,
      submenu: [
        { label: 'About Visual Studio Code' },
        { label: 'Check for Updates...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Settings...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Services' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Hide Visual Studio Code' },
        { label: 'Hide Others' },
        { label: 'Show All' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Quit Visual Studio Code' },
      ],
    },
    {
      label: 'File',
      submenu: [
        { label: 'New Text File' },
        { label: 'New File...' },
        { label: 'New Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Open...' },
        { label: 'Open Folder...' },
        { label: 'Open Workspace from File...' },
        { label: 'Open Recent' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Add Folder to Workspace...' },
        { label: 'Save Workspace As...' },
        { label: 'Duplicate Workspace' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Save' },
        { label: 'Save As...' },
        { label: 'Save All' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Share' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Auto Save' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Revert File' },
        { label: 'Close Editor' },
        { label: 'Close Folder' },
        { label: 'Close' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo' },
        { label: 'Redo' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Cut' },
        { label: 'Сору' },
        { label: 'Copy As' },
        { label: 'Paste' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Find' },
        { label: 'Replace' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Find in Files' },
        { label: 'Replace in Files' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Toggle Line Comment' },
        { label: 'Toggle Block Comment' },
        { label: 'Emmet: Expand Abbreviation' },
        { type: SubMenuType.SEPARATOR },
        { label: 'AutoFill' },
        { label: 'Start Dictation…' },
        { label: 'Emoji & Symbols' },
      ],
    },
    {
      label: 'Selection',
      submenu: [
        { label: 'Select All' },
        { label: 'Expand Selection' },
        { label: 'Shrink Selection' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Copy Line Up' },
        { label: 'Copy Line Down' },
        { label: 'Move Line Up' },
        { label: 'Move Line Down' },
        { label: 'Duplicate Selection' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Add Cursor Above' },
        { label: 'Add Cursor Below' },
        { label: 'Add Cursors to Line Ends' },
        { label: 'Add Next Occurrence' },
        { label: 'Add Previous Occurrence' },
        { label: 'Select All Occurrences' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Switch to Alt+Click for Multi-Cursor' },
        { label: 'Column Selection Mode' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { label: 'Show Tab Bar' },
        { label: 'Show All Tabs' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Command Palette...' },
        { label: 'Open View...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Appearance' },
        { label: 'Editor Layout' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Explorer' },
        { label: 'Search' },
        { label: 'Source Control' },
        { label: 'Run' },
        { label: 'Extensions' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Problems' },
        { label: 'Output' },
        { label: 'Debug Console' },
        { label: 'Terminal' },
        { label: 'Word Wrap' },
        { label: 'Run' },
        { label: 'Terminal' },
      ],
    },
    {
      label: 'Go',
      submenu: [
        { label: 'Back' },
        { label: 'Forward' },
        { label: 'Last Edit Location' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Switch Editor' },
        { label: 'Switch Group' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Go to File...' },
        { label: 'Go to Symbol in Workspace...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Go to Symbol in Editor...' },
        { label: 'Go to Definition' },
        { label: 'Go to Declaration' },
        { label: 'Go to Type Definition' },
        { label: 'Go to Implementations' },
        { label: 'Go to References' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Go to Line/Column...' },
        { label: 'Next Problem' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Previous Problem' },
        { label: 'Next Change' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Previous Change' },
      ],
    },
    {
      label: 'Run',
      submenu: [
        { label: 'Start Debugging' },
        { label: 'Run Without Debugging' },
        { label: 'Stop Debugging' },
        { label: 'Restart Debugging' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Open Configurations' },
        { label: 'Add Configuration...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Step Over' },
        { label: 'Step Into' },
        { label: 'Step Out' },
        { label: 'Continue' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Toggle Breakpoint' },
        { label: 'New Breakpoint' },
        { label: 'Enable All Breakpoints' },
        { label: 'Disable All Breakpoints' },
        { label: 'Remove All Breakpoints' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Install Additional Debuggers...' },
      ],
    },
    {
      label: 'Terminal',
      submenu: [
        { label: 'New Terminal' },
        { label: 'Split Terminal' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Run Task...' },
        { label: 'Run Build Task...' },
        { label: 'Run Active File' },
        { label: 'Run Selected Text' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Show Running Tasks...' },
        { label: 'Restart Running Task...' },
        { label: 'Terminate Task...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Configure Tasks...' },
        { label: 'Configure Default Build Task...' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { label: 'Minimize' },
        { label: 'Zoom' },
        { label: 'Tile Window to Left of Screen' },
        { label: 'Tile Window to Right of Screen' },
        { label: 'Replace Tiled Window' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Remove Window from Set' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Switch Window...' },
        { type: SubMenuType.SEPARATOR },
        { label: 'New Tab' },
        { label: 'Show Previous Tab' },
        { label: 'Show Next Tab' },
        { label: 'Move Tab to New Window' },
        { label: 'Merge All Windows' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Bring All to Front' },
      ],
    },
    {
      label: 'Help',
      submenu: [
        { label: 'Welcome' },
        { label: 'Show All Commands' },
        { label: 'Documentation' },
        { label: 'Editor Playground' },
        { label: 'Show Release Notes' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Keyboard Shortcuts Reference' },
        { label: 'Video Tutorials' },
        { label: 'Tips and Tricks' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Join Us on YouTube' },
        { label: 'Search Feature Requests' },
        { label: 'Report Issue' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Privacy Statement' },
        { type: SubMenuType.SEPARATOR },
        { label: 'Toggle Developer Tools' },
        { label: 'Open Process Explorer' },
      ],
    },
  ],
  [App.BIN]: [
    {
      label: App.BIN,
    },
  ],
  [App.BITWARDEN]: [
    {
      label: App.BITWARDEN,
    },
  ],

  [App.ITERM2]: [
    {
      label: App.ITERM2,
    },
  ],
  [App.OBSIDIAN]: [
    {
      label: App.OBSIDIAN,
    },
  ],
  [App.SPOTIFY]: [
    {
      label: App.SPOTIFY,
    },
  ],
  [App.DOCKER]: [
    {
      label: App.DOCKER,
    },
  ],
}
